client:
  post:
    baseUrl: http://mb1.kosbarokah.com
server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:hsql://localhost:9001/testdb
    username: SA
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles.active: prod
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
secret:
  InthispackagewcreateourfirstclasscalledTokenManagerThisclasswillberesponsibleforthecreationandvalidationoftokensusingiojsonwebtokenJwts
jwtExpirationMs: 36000
logging:
  level:
    root: INFO
    com.wbs: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: kos-app.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz # by date
      max-file-size: 10MB
      max-history: 20
